// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110020201_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CategoryType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int>("EventCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.HasIndex("EventCategoryId");

                    b.ToTable("CategoryType", (string)null);

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            EventCategoryId = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            TypeId = 2,
                            EventCategoryId = 1,
                            Name = "Pop"
                        },
                        new
                        {
                            TypeId = 3,
                            EventCategoryId = 1,
                            Name = "Trap"
                        },
                        new
                        {
                            TypeId = 4,
                            EventCategoryId = 1,
                            Name = "Reggaeton"
                        },
                        new
                        {
                            TypeId = 5,
                            EventCategoryId = 1,
                            Name = "Electronic"
                        },
                        new
                        {
                            TypeId = 6,
                            EventCategoryId = 1,
                            Name = "Metal"
                        },
                        new
                        {
                            TypeId = 7,
                            EventCategoryId = 1,
                            Name = "Cumbia"
                        },
                        new
                        {
                            TypeId = 8,
                            EventCategoryId = 1,
                            Name = "Hip-Hop"
                        },
                        new
                        {
                            TypeId = 9,
                            EventCategoryId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            TypeId = 10,
                            EventCategoryId = 2,
                            Name = "Satire"
                        },
                        new
                        {
                            TypeId = 11,
                            EventCategoryId = 3,
                            Name = "Technology"
                        },
                        new
                        {
                            TypeId = 12,
                            EventCategoryId = 3,
                            Name = "Business"
                        },
                        new
                        {
                            TypeId = 13,
                            EventCategoryId = 3,
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EventStatusStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("#FFFFFF");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventStatusStatusId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserToken");

                    b.HasIndex("VenueId");

                    b.HasIndex("CategoryId", "TypeId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EventCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("EventCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Music"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Stand-up"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("Domain.Entities.EventSector", b =>
                {
                    b.Property<Guid>("EventSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventSectorId");

                    b.HasIndex("EventId");

                    b.HasIndex("SectorId");

                    b.ToTable("EventSector", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EventStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId");

                    b.ToTable("EventStatus", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Scheduled"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Active"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Postponed"
                        },
                        new
                        {
                            StatusId = 4,
                            Name = "Finished"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CategoryType", b =>
                {
                    b.HasOne("Domain.Entities.EventCategory", "EventCategory")
                        .WithMany("CategoryTypes")
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCategory");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.HasOne("Domain.Entities.EventCategory", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EventStatus", null)
                        .WithMany("Events")
                        .HasForeignKey("EventStatusStatusId");

                    b.HasOne("Domain.Entities.EventStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CategoryType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Domain.Entities.EventSector", b =>
                {
                    b.HasOne("Domain.Entities.Event", "Event")
                        .WithMany("EventSectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.Entities.Event", b =>
                {
                    b.Navigation("EventSectors");
                });

            modelBuilder.Entity("Domain.Entities.EventCategory", b =>
                {
                    b.Navigation("CategoryTypes");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Domain.Entities.EventStatus", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
